### ISSUE TITLE
Broken local character

### ISSUE THREAD

**Issue by aliakyurek** [turkish-nlp-suite/turkish-spacy-models#2]
Hello Duygu,
Thanks for the great content on github and youtube.

I've loaded tr_core_web_trf model.
As seen below, "ü" character is printed wrong. What could be the reason?
```
[w for w in nlp("Dün de tatildi.")]
[D�n, de, tatildi, .]
```

**Comment by aliakyurek** [comment]
Hmm I guess this is specific to my environment. :)

**Comment by DuyguA** [comment]
> Hmm I guess this is specific to my environment. :)

Accidents happen, no worries :wink:
