### ISSUE TITLE
Support Spacy 3.6+

### ISSUE THREAD

**Issue by obalais** [turkish-nlp-suite/turkish-spacy-models#3]
Hi there,

Thanks for your amazing work!
Is there any plan to support Spacy 3.6? We would love to use your spacy pipelines for POSTagging but it seems your existing pipelines on Huggingface are scopes to older versions.

Is there anything we can do on our side to help?

**Comment by DuyguA** [comment]
Hellos, thanks for your message!

Yes, I'll do a new training and packaging a bit after new year. I'll have some time during January, plans include several pipelines, a general model, a social media model and possibly a medical NLP pipeline. Changes will include enhancements to POS and dep too. You can either follow me on Linkedin or my dedicated [Turkish NLP website](https://www.turkish-nlp-suite.com). Stay tuned for the upcoming packages 😎 😎😎
