### ISSUE TITLE
Pronouns are not recognized as PRON/PRP

### ISSUE THREAD

**Issue by gokaybiz** [turkish-nlp-suite/turkish-spacy-models#4]
When I try to detect pronouns, they seem to be tagged as "Pers" which stands for person I guess.

Example list of Pers:
```Pers ben
Pers Sen
Pers ben
Pers ben
Pers Sen
Pers sen
Pers ben
Pers ben
Pers onlar
Pers sizler
```

References:
https://huggingface.co/turkish-nlp-suite/tr_core_news_trf
https://cs.nyu.edu/~grishman/jet/guide/PennPOS.html

**Comment by DuyguA** [comment]
Hellos, thanks for the question!

Languages like Turkish with rich morphology usually have two tag sets, coarse (universal tags, same tagset all languages) and fine (tailored up to the language morphology/syntax). In spaCy coarse and fine tags are distinguished by, `token.pos` and `token.tag` attributes. Just like in these examples:

```
>>> doc = nlp("Sen de geldin")
>>> for token in doc:
...   token, token.pos_, token.tag_
... 
(Sen, 'PRON', 'Pers')
(de, 'CCONJ', 'Conj')
(geldin, 'VERB', 'Verb')

>>> doc = nlp("Bunu alın götürün.")
>>> for token in doc:
...   token, token.pos_, token.tag_
... 
(Bunu, 'PRON', 'Demons')
(alın, 'VERB', 'Verb')
(götürün, 'VERB', 'Verb')
(., 'PUNCT', 'Punc')

>>> doc = nlp("Kendileri gelsinler.")
>>> for token in doc:
...   token, token.pos_, token.tag_
... 
(Kendileri, 'PRON', 'Reflex')
(gelsinler, 'VERB', 'Verb')
(., 'PUNCT', 'Punc')

```

Your guess is correct definitely :wink:   , `Pers` is for personal pronouns and all tags come from BOUN Treebank, that is used this package. More details about the tagging scheme can be found under the [treebank docs](https://universaldependencies.org/treebanks/tr_boun/index.html). Another example for coarse tagset is the Penn Tagset - coming from Penn Treebank and tailored for English, as you linked. If you need more details about spaCy attributes, I suggest the [official documentation](https://spacy.io/usage/linguistic-features). If you need more details about UD, I published a video in my Youtube channel (don't remember the video name :grin: ). Hope it's enough info, again thanks for visiting!
