### ISSUE TITLE
Error installing with PIP

### ISSUE THREAD

**Issue by hakanoktay** [turkish-nlp-suite/turkish-spacy-models#5]
Hi, 
when I try to install the module with "pip" I get the following error.

```
pip install https://huggingface.co/turkish-nlp-suite/tr_core_news_lg/resolve/main/tr_core_news_lg-any-py3-none-any.whl
```
```
ERROR: Invalid requirement: 'tr-core-news-lg==any': Expected end or semicolon (after name and no valid version specifier)
    en-core-news-lg==any
```
- python 3.11
- pip 24.2
- macOS M1 chip

Thank you for the answer.

**Comment by DuyguA** [comment]
Hellos, thanks for your message!

A recent update with setuptools broke installation of quite many `whl` files.  There's a temporary workaround here: https://huggingface.co/turkish-nlp-suite/tr_core_news_trf/discussions/1  , however I'll tweak & rename the whl file by weekend. If it's urgent please use the workaround, if not please wait for the weekend :wink:

**Comment by hakanoktay** [comment]
Thank you very much, Duygu.
I haven't tested it yet, but I think it worked.

For those who have this problem, the solution is as follows.

```
1. I downloaded the "whl" file from here. . 
   download: https://huggingface.co/turkish-nlp-suite/tr_core_news_trf/tree/main
   file: tr_core_news_trf-any-py3-none-any.whl
```
```
2. I changed the file name to the following (version 1.0.0 added). 
   file: tr_core_news_trf-1.0.0-py3-none-any.whl
```
```
3. I run PIP in the directory where the file is located.
   command: pip install ./tr_core_news_trf-1.0.0-py3-none-any.whl
```

**Comment by DuyguA** [comment]
OK, I updated the wheel file name and documentation a bit,  all model repos has now new PIP instructions for installing. Thanks for your visit again :blush:
